version: '3'
services:
  app:
    build: .
    ports:
      - '5000:5000'
    depends_on:
      - db
    environment:
      - DB_HOST=db
      - DB_PORT=3306
      - DB_NAME=flask_app
      - DB_USER=root
      - DB_PASSWORD=example

#   db:
#     image: mysql:5.7
#     restart: always
#     environment:
#       MYSQL_DATABASE: flask_app
#       MYSQL_USER: root
#       MYSQL_PASSWORD: example
#       MYSQL_ROOT_PASSWORD: example
#     volumes:
#       - db_data:/var/lib/mysql

# volumes:
#   db_data:
